### ISSUE TITLE
The plugin doesn't work for me with Gradle 9.5.1.

### ISSUE THREAD

**Issue by dirk-w** [asciidoctor/asciidoctor-gradle-plugin#774]
Hi,

I’ve been looking for a solution for quite some time and have tried a few things. I also found this issue but don't see the solution. 
[https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/770](https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/770)
The following build file works perfectly with Gradle 8.14, but when I migrate to Gradle 9.5, I get the following error message:

> The StartParameter.isConfigurationCacheRequested property has been deprecated

This Stack:
`
java.lang.NoClassDefFoundError: Could not initialize class groovyx.net.http.HttpConfigs
Exception java.lang.NoClassDefFoundError: groovy/util/slurpersupport/GPathResult
`
this is my buildfile, I have changed to the (in my opinion) newest versions, but that does not work
```
plugins {
	id 'org.asciidoctor.jvm.pdf' version "5.0.0-alpha.1"
	id 'org.asciidoctor.jvm.gems' version "5.0.0-alpha.1"
	id 'org.asciidoctor.jvm.convert' version '4.0.5'
}
// 4.0.5 -> 5.0.0-alpha.1

apply plugin: 'java'
group = 'url.it.stc.doc'
version = file('./version.txt').text.trim()

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

repositories {
    mavenCentral()
	ruby.gems()
}

jar {
	enabled = false
}

//3.15.0 -> 5.1.0
dependencies {
	asciidoctorGems 'rubygems:rouge:5.1.0'
}

//yyyyMMddHHmmss
static def getDate() {
	return new Date().format('dd.MM.yyyy')
}

// 2.5.6 -> asciidoctorj 3.0.1
// 2.3.0 -> asciidoctorj-pdf 2.3.26
// 2.2.3 -> asciidoctorj-diagram 3.0.1
asciidoctorPdf {
	baseDirFollowsSourceFile()
	asciidoctorj {
		modules {
			asciidoctorj {
				version "3.0.1"
			}
			pdf {
				version "2.3.26"
			}
			diagram {
				version "3.0.1"
			}
		}
		requires 'rouge'
		options safe: 'unsafe'
		attributes 'build-gradle': file('build.gradle'),
			'sourcedir': project.sourceSets.main.java.srcDirs[0],
			'endpoint-url': 'https://url.it',
			'source-highlighter': 'rouge',
			'imagesdir': './images',
			'toc': 'left',
			'icons': 'font',
			'idprefix': '',
			'idseparator': '-',
			':revnumber:': version,
			'revdate': getDate()
	}
}

// 2.5.6 -> asciidoctorj 3.0.1
// 2.3.0 -> asciidoctorj-pdf 2.3.26
// 2.2.3 -> asciidoctorj-diagram 3.0.1
// 9.3.8.0 -> JRuby 9.4.14.0
asciidoctor {
	baseDirFollowsSourceFile()
	asciidoctorj {
		modules {
			asciidoctorj {
				version "3.0.1"
			}
			pdf {
				version "2.3.26"
			}
			diagram {
				version "3.0.1"
			}
		}
		requires "rouge"
		options safe: 'unsafe'

		// the asciidoctor task depends on this gem
		//requires = ['asciidoctor-diagram']
		//gemPath = jrubyPrepare.outputDir
		attributes \
	    'build-gradle': file('build.gradle'),
			'jrubyVersion': '9.4.14.0',
			'sourcedir': project.sourceSets.main.java.srcDirs[0],
			'endpoint-url': 'https://url.it',
			'imagesdir': 'images',
			'toc': 'left',
			'icons': 'font',
			'setanchors': '',
			'idprefix': '',
			'idseparator': '-',
			'docinfo': 'shared',
			':revnumber:': version,
			'revdate': getDate()
	}

}

tasks.register('genHtmlDoc',GradleBuild) {
	description = "generate only html documentation"
	dependsOn('asciidoctor')
}

tasks.register('genAllDoc',GradleBuild) {
	description = "generates html and pdf documentation"
	dependsOn('asciidoctor')
	dependsOn('asciidoctorPdf')
}

```
I would be grateful for any information.
Thanks in advance

**Comment by ysb33r** [comment]
The issue is introduced by the usage of httpbuilder-ng somewhere - it might be the use of an older version of the JRuby Simplified Plugin.

I'll look into it.

**Comment by ysb33r** [comment]
As a workaround try to add
```
plugins {
  id 'org.ysb33r.jruby.resolver' version '2.4.1' apply false
}
```

**Comment by dirk-w** [comment]
Thank's for support, but workaround won't work.
The output changed to 

`Could not find method asciidoctorGems() for arguments [rubygems:rouge:5.1.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
`
Stacktrace shows the same output

**Comment by ysb33r** [comment]
This is fixed in the final 5.0.0. It will be out hopefully by end of this week.
