### ISSUE TITLE
Incompatibility with gradle 7.1+

### ISSUE THREAD

**Issue by bric3** [asciidoctor/asciidoctor-gradle-plugin#626]
Upgrading a build to Gralde 7.1+ makes it fails.

To reproduce simply create a `build.gradle.kts` script like this :

```kotlin
plugins {
    id("org.asciidoctor.jvm.revealjs") version "3.3.2"
}

repositories {
    mavenCentral()
    ruby.gems()
}
```

Before Gradle 7.1 this works, after they running the reveal js task fails :

```
$ ./gradlew asciidoctorRevealJs --stacktrace
Starting a Gradle Daemon, 1 incompatible and 4 stopped Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
'void org.gradle.wrapper.PathAssembler.<init>(java.io.File)'

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
java.lang.NoSuchMethodError: 'void org.gradle.wrapper.PathAssembler.<init>(java.io.File)'
        at org.ysb33r.grolifant.internal.downloader.ArtifactDownloader.getFromCache(ArtifactDownloader.groovy:135)
        at org.ysb33r.grolifant.api.git.GitRepoArchiveDownloader.getArchiveRoot(GitRepoArchiveDownloader.groovy:99)
        at org.asciidoctor.gradle.jvm.slides.RevealJSExtension$_resolveViaGitHub_closure3.doCall(RevealJSExtension.groovy:107)
```

**Comment by ghilainm** [comment]
Same issue with Gradle 6.9.1. It seems to be linked to cache as using --no-build-cache solve the issue.

**Comment by ysb33r** [comment]
Please try 4.0.0-alpha.1 and tell me if the problem still exists

**Comment by bric3** [comment]
@ysb33r Hi, just tested the reproducer above and it seem to work on Gradle 8.5.

Although I have not been exhaustive in this test as I don't have any presentation using reveal js at this time.

**Comment by ysb33r** [comment]
Full revealjs support should be back in 4.1.0
