### ISSUE TITLE
revealjs 2.2.0 incompatible with asciidoctor 2.0.0

### ISSUE THREAD

**Issue by jagedn** [asciidoctor/asciidoctor-gradle-plugin#380]
If I try to include the revealJs plugin in this project https://gitlab.com/puravida-asciidoctor/asciidoctor-amazon-template/ 

including the plugin into the build.gradle (all remains the same)

    plugins {
        id 'org.asciidoctor.jvm.convert' version '2.2.0'
        id 'org.asciidoctor.jvm.epub' version '2.2.0'
        id 'org.asciidoctor.jvm.pdf' version '2.2.0'
        id 'org.asciidoctor.jvm.revealjs' version '2.2.0'
    }

then all asciidoctor plugins fail with:

`Exception in thread "main" java.lang.NoSuchMethodError: org.asciidoctor.Asciidoctor$Factory.create(Ljava/lang/String;)Lorg/asciidoctor/Asciidoctor;
	at org.asciidoctor.gradle.remote.AsciidoctorJavaExec.getAsciidoctorInstance(AsciidoctorJavaExec.groovy:99)
	at org.asciidoctor.gradle.remote.AsciidoctorJavaExec.run(AsciidoctorJavaExec.groovy:56)
	at org.asciidoctor.gradle.remote.AsciidoctorJavaExec.main(AsciidoctorJavaExec.groovy:47)`

**Comment by ysb33r** [comment]
That is correct. You'll have to wait for 3.0.0-alpha.1 (a couple of weeks more) for your first supported taste of Asciidoctor 2.0.

**Comment by jagedn** [comment]
ah, ok, thanks
as others backens work fine with asciidoctor v2.0.0 I supposed this will be also

**Comment by ysb33r** [comment]
The reason the others work is that they don't use additional GEMs. If you were, for instance, to use the asciidoctor-bibtex GEM with any of the others you'll see the same thing.
