### ISSUE TITLE
Using the asciidoctor task causes the Gradle daemon to crash

### ISSUE THREAD

**Issue by wolfs** [asciidoctor/asciidoctor-gradle-plugin#253]
On our CI infrastructure (https://builds.gradle.org/) we are using the Gradle daemon between builds. We are seeing build failures with the message
```
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
```
See for example this build: https://builds.gradle.org/viewLog.html?buildId=13925992&buildTypeId=Gradle_Check_Parallel_Java7_Ibm_Linux_osgi&tab=buildLog&_focus=1163#_state=1159

All the crashes we analyzed so far seem to be caused by the [`jffi`](https://github.com/jnr/jffi) library:
```
Stack: [0x00007f6318bfc000,0x00007f6318cfd000],  sp=0x00007f6318cfaa50,  free space=1018k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [ld-linux-x86-64.so.2+0xa01e]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 5976  java.lang.ClassLoader$NativeLibrary.find(Ljava/lang/String;)J (0 bytes) @ 0x00007f631914d44c [0x00007f631914d400+0x4c]
j  java.lang.ClassLoader.findNative(Ljava/lang/ClassLoader;Ljava/lang/String;)J+49
v  ~StubRoutines::call_stub
j  com.kenai.jffi.Foreign.freeMemory(J)V+0
j  com.kenai.jffi.MemoryIO.freeMemory(J)V+1
j  com.kenai.jffi.NativeMethods$ResourceHolder.finalize()V+8
J 23913% C2 java.lang.ref.Finalizer$FinalizerThread.run()V (55 bytes) @ 0x00007f631b62e838 [0x00007f631b62e580+0x2b8]
v  ~StubRoutines::call_stub
```

The problem seems to appear after a build which ran an asciidoctor task.

IIUC, asciidoctor uses JRuby and JRuby uses jffi. I think that this is the same or a related problem: https://github.com/jruby/jruby/issues/4506

If I understand https://github.com/jruby/jruby/issues/4506 correctly, the crash happens when the JNI library get unloaded when there are still resources from jffi awaiting to be finalized. When the finalizer kicks in it tries to use the unloaded JNI library and causes a crash of the JVM.

Can we fix this problem on the asciidoctor plugin side?

One possible solution would be if the asciidoctor plugin would make sure that the JRuby runtime would be loaded in a different JVM to the Gradle daemon JVM. This could maybe be achieved by using the [Worker API](https://guides.gradle.org/using-the-worker-api/). WDYT?

**Comment by wolfs** [comment]
I forgot to mention that we are currently using the asciidoctor gradle plugin version 1.5.3: https://github.com/gradle/gradle/blob/135ac7bd3cfe91b57d2a2e4ed759e2af29b6ea45/buildSrc/subprojects/build/build.gradle.kts#L6
Our builds run with Java 8 and we saw the crashes on Linux.

**Comment by eriwen** [comment]
Note that this may be totally different in the plugin version 2.0, which IIRC uses the Worker API. I recently tried using the 2.0 alpha 2 for the Gradle build with no success.

**Comment by ysb33r** [comment]
Hi Stefan, 
Try out 2.0-alpha.2.


Sent from my Samsung device

-------- Original message --------

**Comment by blindpirate** [comment]
Today we also see several OOMs on CI. According to the thread dumps, it seems that `jffi` finalizer thread also holds some `ClassLoader`s, which can't be GCed and occupies hundreds of MB memory. I really think it's necessary to run JRuby operations in another process.

![image](https://user-images.githubusercontent.com/12689835/43580391-e9f836ca-9687-11e8-9189-7abe3034b1b0.png)

**Comment by ysb33r** [comment]
> Note that this may be totally different in the plugin version 2.0, which IIRC uses the Worker API. I recently tried using the 2.0 alpha 2 for the Gradle build with no success.

If you say no success, what does this mean?

- You are still seeing OOMs?
- You are seeing JFFI errors?

When you ran alpha2 did you use `org.asciidoctor.convert` or `org.asciidoctor.jvm.convert`? The former for compatitiblity with the existing 1.5x series, but the latter plugin is prefered.  The latter is also where you can configure process mode (`IN_PROCESS`, `OUT_OF_PROCESS`, `JAVA_EXEC`).

Also in alpha.2 the `org.asciidoctor.convert` uses the same memory model as in 1.5.x, but in the upcoming alpha.3 it will use `JAVA_EXEC` under the hood.

**Comment by ysb33r** [comment]
I had a quick look, then pulled your branch. I can spot a number of issues. The firsyt give-away is that you are still running with the compatiiblity plugin as per `--warning-mode=all`:

```
You are using one or more deprecated Asciidoctor task or plugins. These will be removed in a future release. To help you migrate we have compiled some tips for you based upon your current usage:

  - 'org.asciidoctor.convert' is deprecated. When you have time please switch over to 'org.asciidoctor.jvm.convert'.
  - jcenter() is no longer added by default. If you relied on this behaviour in the past, please add jcenter() to the repositories block.
  - You have used 'setBackends'. When upgrading you will need to: Use outputOoptons.setBackends
  - You have used 'backends'. When upgrading you will need to: Use outputOoptons.setbackends
```

 I am going to see if I can make some changes and send a PR to your branch.

**Comment by ysb33r** [comment]
Imade some changes, but I'm seeing this error when trying out the branch that @eriwen provided:

```
java.lang.IncompatibleClassChangeError: Class org.gradle.api.internal.project.DefaultProject_Decorated does not implement the requested interface org.gradle.api.internal.file.FileOperations
```

Is there something special in the SNAPSHOT of Gradle 4.10 that might be incompatible with the plugin?
(Using JDK10).

**Comment by wolfs** [comment]
@ysb33r I guess that is due to https://github.com/gradle/gradle/issues/6027.

**Comment by ysb33r** [comment]
Thanks @wolfs. I am going to add the PR that @lptr used for the packer-gradle-plugin and see if we can get it in before alpha.3 is released.

**Comment by ysb33r** [comment]
Before releasing 2.0.alpha.3 we applied @lptr's Groovy workaround to the asciidoctor build - we compile with groovy-2.4.15. Yet I am still seeing the same problem.

**Comment by ysb33r** [comment]
Just saw https://issues.apache.org/jira/browse/GROOVY-8732

**Comment by wolfs** [comment]
@ysb33r We ended up fixing the incompatibility on the Gradle side. This will be in `4.10`. Can you try out if `4.10-20180807192046+0000` works?

**Comment by ysb33r** [comment]
@wolfs Now I get a different error:

```
* Where:
Build file '/Users/schalkc/Projects/GradleSource/buildSrc/build.gradle.kts' line: 68

* What went wrong:
Script compilation error:

  Line 68:                 val mainSourceSet = project.java.sourceSets[SourceSet.MAIN_SOURCE_SET_NAME]
                                                            ^ Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
                                                                public val Project.sourceSets: SourceSetContainer defined in org.gradle.kotlin.dsl
```

This is using a working copy of the branch that @eriwen pointed me at. The most interesting part of the stack trace is:

```
* Exception is:
ScriptCompilationException(errors=[ScriptCompilationError(message=Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public val Project.sourceSets: SourceSetContainer defined in org.gradle.kotlin.dsl, location=/private/var/folders/jy/ls4wb8pd3tgg10f8vr2q27_h0000gn/T/gradle-kotlin-dsl-14674376518901919392.tmp/build.gradle.kts (68:50))])
        at org.gradle.kotlin.dsl.support.KotlinCompilerKt.compileKotlinScriptToDirectory(KotlinCompiler.kt:97)
        at org.gradle.kotlin.dsl.execution.ResidualProgramCompiler.compileScript(ResidualProgramCompiler.kt:508)
        at org.gradle.kotlin.dsl.execution.ResidualProgramCompiler.emitStage2ProgramFor(ResidualProgramCompiler.kt:216)
        at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost$compileSecondStageScript$cacheDir$1.invoke(Interpreter.kt:471)
        at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost$compileSecondStageScript$cacheDir$1.invoke(Interpreter.kt:345)
        at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator$InterpreterHost$cacheDirFor$1.invoke(KotlinScriptEvaluator.kt:246)
        at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator$InterpreterHost$cacheDirFor$1.invoke(KotlinScriptEvaluator.kt:145)
        at org.gradle.kotlin.dsl.cache.ScriptCache$cacheDirFor$3.execute(ScriptCache.kt:51)
        at org.gradle.kotlin.dsl.cache.ScriptCache$cacheDirFor$3.execute(ScriptCache.kt:28)
        at org.gradle.cache.internal.DefaultPersistentDirectoryCache$Initializer.initialize(DefaultPersistentDirectoryCache.java:109)
        at org.gradle.cache.internal.FixedSharedModeCrossProcessCacheAccess$1.run(FixedSharedModeCrossProcessCacheAccess.java:85)
        at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.doWriteAction(DefaultFileLockManager.java:207)
        at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.writeFile(DefaultFileLockManager.java:197)
        at org.gradle.cache.internal.FixedSharedModeCrossProcessCacheAccess.open(FixedSharedModeCrossProcessCacheAccess.java:83)
        at org.gradle.cache.internal.DefaultCacheAccess.open(DefaultCacheAccess.java:141)
        at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:78)
        at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:42)
        at org.gradle.cache.internal.DefaultCacheFactory.doOpen(DefaultCacheFactory.java:95)
        at org.gradle.cache.internal.DefaultCacheFactory.open(DefaultCacheFactory.java:69)
        at org.gradle.cache.internal.DefaultCacheRepository$PersistentCacheBuilder.open(DefaultCacheRepository.java:124)
        at org.gradle.kotlin.dsl.cache.ScriptCache.cacheDirFor(ScriptCache.kt:52)
        at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator$InterpreterHost.cacheDirFor(KotlinScriptEvaluator.kt:229)
        at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator$InterpreterHost.cachedDirFor(KotlinScriptEvaluator.kt:218)
        at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.compileSecondStageScript(Interpreter.kt:442)
        at Program.loadSecondStageFor(Unknown Source)
        at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.evaluateSecondStageOf(Interpreter.kt:399)
        at Program.execute(Unknown Source)
        at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.eval(Interpreter.kt:492)
        at org.gradle.kotlin.dsl.execution.Interpreter.eval(Interpreter.kt:162)
        at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator.evaluate(KotlinScriptEvaluator.kt:108)
        at org.gradle.kotlin.dsl.provider.KotlinScriptPluginFactory$create$1.invoke(KotlinScriptPluginFactory.kt:51)
        at org.gradle.kotlin.dsl.provider.KotlinScriptPluginFactory$create$1.invoke(KotlinScriptPluginFactory.kt:36)
        at org.gradle.kotlin.dsl.provider.KotlinScriptPlugin.apply(KotlinScriptPlugin.kt:34)
        at org.gradle.configuration.BuildOperationScriptPlugin$1$1.run(BuildOperationScriptPlugin.java:69)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.configuration.BuildOperationScriptPlugin$1.execute(BuildOperationScriptPlugin.java:66)
        at org.gradle.configuration.BuildOperationScriptPlugin$1.execute(BuildOperationScriptPlugin.java:63)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:48)
        at org.gradle.configuration.BuildOperationScriptPlugin.apply(BuildOperationScriptPlugin.java:63)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:41)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject.run(LifecycleProjectEvaluator.java:105)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:68)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:687)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:140)
        at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:60)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:41)
        at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuild.run(DefaultGradleLauncher.java:274)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)

```

**Comment by wolfs** [comment]
@ysb33r I guess that is due to the fact that the Gradle branch is too old. Could you merge the `master` branch into Eric's branch? Do you have the work you did up to now available somewhere, so I could have a look?

**Comment by ysb33r** [comment]
@wolfs https://github.com/ysb33r/gradle-1/tree/asciidoctor-gradle-plugin-2.0 (before merging anythinf from master)

**Comment by wolfs** [comment]
https://github.com/ysb33r/gradle-1/tree/asciidoctor-gradle-plugin-2.0 seem be identical to gradle/gradle's `master` branch.

**Comment by ysb33r** [comment]
Having merged form master, I have made some progress. STuck on a new error: `Exception in thread "main" java.lang.ClassNotFoundException: com.google.common.collect.ImmutableSet$SerializedForm`, but am going to investigate that a bit more. Will try to make a simplified project at first to see if it can be reproduces outside of the Gradle docs project itself.

**Comment by ysb33r** [comment]
> https://github.com/ysb33r/gradle-1/tree/asciidoctor-gradle-plugin-2.0 seem be identical to gradle/gradle's master branch.

@wolfs https://github.com/ysb33r/gradle-1/tree/eriwen/docs/asciidoctor-gradle-plugin-2.0

**Comment by wolfs** [comment]
I guess the error comes from the worker? I guess it doesn't have guava on its classpath.

**Comment by ysb33r** [comment]
It is going to take me a while to debug this - I dont really have much time in the next 10 days. 

I suspect these issues are now more down to configuration of the Asciidoctor extensions used in the Gradle build rather than the Asciidoctor Gradle plugin itself.

**Comment by ysb33r** [comment]
@wolfs Where can I find the soruce for `org.gradle:docs-asciidoctor-extensions:0.3.0` ? I think it is part of the problem. The AsciidoctorJ extension API is different between 1.5.x and 1.6-alpha.x.

**Comment by wolfs** [comment]
@ysb33r I think we didn't open source those, yet. Right @eriwen?

**Comment by ysb33r** [comment]
I have made some progress. I set the `asciidoctorj.version = '1.5.7'` on the task and now at least the asciidoctor-extensions are loaded. I still have one issue w.r.t. Asciidoctor files being included. Will investigate that next. 

Luckily we can now make the build fail if an Asciidoc file is not found, so it helps to tracks down issues.

**Comment by eriwen** [comment]
@wolfs correct, I hope to wrap these in a gift to the community soon, but I haven't had time to make the wrapping paper. 

@ysb33r Here's a zip containing the project you can use. https://www.dropbox.com/s/gu8qcqayoxvugui/docs-asciidoctor-extensions.zip?dl=0 

Sorry for the trouble here.

**Comment by ysb33r** [comment]
> Sorry for the trouble here.

It's no trouble - it is a good use case.

**Comment by ysb33r** [comment]
I am not expecting this to crash with 1.5.9.1. Closing this.

**Comment by wolfs** [comment]
@ysb33r Awesome! What are the changes in 1.5.9.1 which would prevent JRuby from crashing the Gradle daemon?

**Comment by ysb33r** [comment]
Later version of JRuby + the fact that AsciidoctorJ runs out of process.
