### ISSUE TITLE
(NoMethodError) undefined method `start_with?'

### ISSUE THREAD

**Issue by kuniss** [asciidoctor/asciidoctor-gradle-plugin#562]
When I bumping the Asciidoctor Gradle pugin version from 1.5.7 (where all works well) to 1.6.1 or 2.4.0 I get this error with slightly different stack traces for both versions.
The asciidoctor task has not been changed inbetween the version changes. It is defined as follows, nothig special:
```
asciidoctor {
    dependsOn adocImports, filterAsciidoc  
    def relImagesDir = './doc/images'
    sourceDir preprocessedAsciidocDir
    outputDir = file('build/adoc')
    
    attributes 'source-highlighter': 'coderay',
        toc : 'left',
        toclevels : '5', 
        imagesdir: relImagesDir, 
        docinfo1: '',
        docinfodir: adocImports.destinationDir,
        nofooter: '',
        webfonts: false // avoid link to Google for webfont loading for off-line viewing
}
```

Am I doing something wrong?

Here are the stack traces:
Version 1.6.1
```
> Task :asciidoctor
Aug 10, 2020 3:36:57 PM org.asciidoctor.internal.JRubyAsciidoctor convertFile
SCHWERWIEGEND: (NoMethodError) undefined method 'start_with?' for #<Java::JavaIo::File:0x4971f459>
Exception in thread "main" org.asciidoctor.gradle.backported.AsciidoctorRemoteExecutionException: Error running Asciidoctor whilst attempting to process C:\Users\denis.kuniss\ProbaseRSSWorkspace\doc-probase-store\build\adoc\user-guider.adoc using backend html5
	at org.asciidoctor.gradle.backported.AsciidoctorJavaExec$_convertFiles_closure3.doCall(AsciidoctorJavaExec.groovy:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:434)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2125)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2110)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2163)
	at org.asciidoctor.gradle.backported.AsciidoctorJavaExec.convertFiles(AsciidoctorJavaExec.groovy:56)
	at org.asciidoctor.gradle.backported.AsciidoctorJavaExec.access$0(AsciidoctorJavaExec.groovy)
	at org.asciidoctor.gradle.backported.AsciidoctorJavaExec$_run_closure2.doCall(AsciidoctorJavaExec.groovy:50)
	at org.asciidoctor.gradle.backported.AsciidoctorJavaExec$_run_closure2.call(AsciidoctorJavaExec.groovy)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2125)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2110)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2151)
	at org.asciidoctor.gradle.backported.AsciidoctorJavaExec.run(AsciidoctorJavaExec.groovy:48)
	at org.asciidoctor.gradle.backported.AsciidoctorJavaExec.main(AsciidoctorJavaExec.groovy:194)
Caused by: org.asciidoctor.internal.AsciidoctorCoreException: org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method 'start_with?' for #<Java::JavaIo::File:0x4971f459>
	at org.asciidoctor.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:498)
	at org.asciidoctor.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:469)
	at org.asciidoctor.gradle.backported.AsciidoctorJavaExec$_convertFiles_closure3.doCall(AsciidoctorJavaExec.groovy:61)
	... 22 more
Caused by: org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method 'start_with?' for #<Java::JavaIo::File:0x4971f459>
	at RUBY.absolute_path?(uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor/path_resolver.rb:145)
	at RUBY.normalize_system_path(uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_node.rb:467)
	at RUBY.docinfo(uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor/document.rb:1299)
	at RUBY.document(uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor/converter/html5.rb:113)
	at RUBY.convert(uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor/converter/base.rb:38)
	at RUBY.convert(uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor/document.rb:1190)
	at RUBY.convert(uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1521)
	at RUBY.convert_file(uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1595)
	at org.jruby.RubyIO.open(org/jruby/RubyIO.java:1157)
	at RUBY.convert_file(uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1595)
```

Version 2.4.0
```
> Task :asciidoctor
Aug 10, 2020 3:41:39 PM org.asciidoctor.internal.JRubyAsciidoctor convertFile
SCHWERWIEGEND: (NoMethodError) undefined method 'start_with?' for #<Java::JavaIo::File:0x678a9516>
Exception in thread "main" org.asciidoctor.gradle.remote.AsciidoctorRemoteExecutionException: Error running Asciidoctor whilst attempting to process C:\Users\denis.kuniss\ProbaseRSSWorkspace\doc-probase-store\build\adoc\user-guider.adoc using backend html5
	at org.asciidoctor.gradle.remote.AsciidoctorJavaExec$_convertFiles_closure4.doCall(AsciidoctorJavaExec.groovy:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:434)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2125)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2110)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2163)
	at org.asciidoctor.gradle.remote.AsciidoctorJavaExec.convertFiles(AsciidoctorJavaExec.groovy:78)
	at org.asciidoctor.gradle.remote.AsciidoctorJavaExec.access$1(AsciidoctorJavaExec.groovy)
	at org.asciidoctor.gradle.remote.AsciidoctorJavaExec$_run_closure3.doCall(AsciidoctorJavaExec.groovy:70)
	at org.asciidoctor.gradle.remote.AsciidoctorJavaExec$_run_closure3.call(AsciidoctorJavaExec.groovy)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2125)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2110)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2151)
	at org.asciidoctor.gradle.remote.AsciidoctorJavaExec.run(AsciidoctorJavaExec.groovy:65)
	at org.asciidoctor.gradle.remote.AsciidoctorJavaExec.main(AsciidoctorJavaExec.groovy:47)
Caused by: org.asciidoctor.internal.AsciidoctorCoreException: org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method 'start_with?' for #<Java::JavaIo::File:0x678a9516>
	at org.asciidoctor.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:498)
	at org.asciidoctor.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:469)
	at org.asciidoctor.gradle.remote.AsciidoctorJavaExec$_convertFiles_closure4.doCall(AsciidoctorJavaExec.groovy:83)
	... 22 more
Caused by: org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method `start_with?' for #<Java::JavaIo::File:0x678a9516>
	at RUBY.absolute_path?(uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor/path_resolver.rb:145)
	at RUBY.normalize_system_path(uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_node.rb:467)
	at RUBY.docinfo(uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor/document.rb:1299)
	at RUBY.document(uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor/converter/html5.rb:113)
	at RUBY.convert(uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor/converter/base.rb:38)
	at RUBY.convert(uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor/document.rb:1190)
	at RUBY.convert(uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1521)
	at RUBY.convert_file(uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1595)
	at org.jruby.RubyIO.open(org/jruby/RubyIO.java:1157)
	at RUBY.convert_file(uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1595)
```

**Comment by mojavelinux** [comment]
The issue here is that the value you are passing a File object to the `docinfodir` attribute. That attribute only accepts a string. So you need to call `.absolutePath` on it at assignment.

**Comment by kuniss** [comment]
Thanks for the fast response. I will try it tomorrow at work. :smile: 

However, shouldn't such a mis-configuration result in proper error message than a dynamic ruby method call failure?
 
I really appreciate all the work that have been done around asciidoc, so this is not bashing! I was just wondering. And an answer, like "contribute and fix it, if it bothers you" is absolutely OK for me. :smiley:

**Comment by mojavelinux** [comment]
If you think that attribute value should be checked, then sure. However, generally attributes are schemaless and expected to have the right type. There are hundreds of potential values to check, and checking them for valid types is just not a path we have taken thus far.

**Comment by kuniss** [comment]
OK, I understand.
I'm still wondering a little bit, why it then have worked with 1.5.7...
Let me try tomorrow.

**Comment by mojavelinux** [comment]
The property from which you are taking the value may have had a different type. I don't know for sure.

**Comment by kuniss** [comment]
Applying your hint, it works well now. Thanks again!

For documentation purposes in case others have similar problems, here is what I've changed:
```
asciidoctor {
    dependsOn adocImports, filterAsciidoc  
    sourceDir preprocessedAsciidocDir
    outputDir = file('build/adoc')
    
    attributes 'source-highlighter': 'coderay',
        toc : 'left',
        toclevels : '5', 
        docinfo1: '',
        docinfodir: adocImports.destinationDir.absolutePath,
        nofooter: '',
        webfonts: false // avoid link to Google for webfont loading for off-line viewing
 }
```
